#PROJETO A SAFRA ANTES DA COLHEITA: DA PARA PREVER A PRODUTIVIDADE DA SOJA SÓ COM DADOS PUBLICOS?

In [49]:
#Importando bibliotecas
import sidrapy


#Importando a tabela 5457 do SIDRA (SITE IBGE) com os dados de produção de soja no estado de São Paulo nos últimos 12 anos
dados_soja = sidrapy.get_table(
    table_code="5457",
    territorial_level="6",
    ibge_territorial_code="in n3 35",
    variable="112,216",
    classifications= {"782": "40124"},
    period="last 12"
)

In [50]:
#Verificar colunas do dataframe
dados_soja.columns

Index(['NC', 'NN', 'MC', 'MN', 'V', 'D1C', 'D1N', 'D2C', 'D2N', 'D3C', 'D3N',
       'D4C', 'D4N'],
      dtype='str')

In [51]:
#Verificando o dataframe
dados_soja.head()

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Município (Código),Município,Ano (Código),Ano,Variável (Código),Variável,Produto das lavouras temporárias e permanentes...,Produto das lavouras temporárias e permanentes
1,6,Município,33,Quilogramas por Hectare,-,3500105,Adamantina - SP,2014,2014,112,Rendimento médio da produção,40124,Soja (em grão)
2,6,Município,1006,Hectares,-,3500105,Adamantina - SP,2014,2014,216,Área colhida,40124,Soja (em grão)
3,6,Município,33,Quilogramas por Hectare,-,3500105,Adamantina - SP,2015,2015,112,Rendimento médio da produção,40124,Soja (em grão)
4,6,Município,1006,Hectares,-,3500105,Adamantina - SP,2015,2015,216,Área colhida,40124,Soja (em grão)

In [52]:
#Mostrando as ultimas linhas do dataframe
dados_soja.tail()

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
15404,6,Município,1006,Hectares,400,3557303,Estiva Gerbi - SP,2023,2023,216,Área colhida,40124,Soja (em grão)
15405,6,Município,33,Quilogramas por Hectare,3900,3557303,Estiva Gerbi - SP,2024,2024,112,Rendimento médio da produção,40124,Soja (em grão)
15406,6,Município,1006,Hectares,500,3557303,Estiva Gerbi - SP,2024,2024,216,Área colhida,40124,Soja (em grão)
15407,6,Município,33,Quilogramas por Hectare,3900,3557303,Estiva Gerbi - SP,2025,2025,112,Rendimento médio da produção,40124,Soja (em grão)
15408,6,Município,1006,Hectares,520,3557303,Estiva Gerbi - SP,2025,2025,216,Área colhida,40124,Soja (em grão)

In [53]:
#Verificando os dados gerais do dataframe
dados_soja.info()

<class 'pandas.DataFrame'>
RangeIndex: 15409 entries, 0 to 15408
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NC      15409 non-null  str
 1   NN      15409 non-null  str
 2   MC      15409 non-null  str
 3   MN      15409 non-null  str
 4   V       15409 non-null  str
 5   D1C     15409 non-null  str
 6   D1N     15409 non-null  str
 7   D2C     15409 non-null  str
 8   D2N     15409 non-null  str
 9   D3C     15409 non-null  str
 10  D3N     15409 non-null  str
 11  D4C     15409 non-null  str
 12  D4N     15409 non-null  str
dtypes: str(13)
memory usage: 3.1 MB

In [54]:
#Renomeando as colunas do dataframe para facilitar a manipulação dos dados
dados_soja.rename(columns={"NC": "Nível Territorial (Código)", "NN": "Nível Territorial (Nome)", "MC": "Unidade de Medida (Código)", "MN": "Unidade de Medida (Nome)", "V": "Valor", "D1C": "Municipio (Código)", "D1N": "Municipio ", "D2C": "Ano Codigo", "D2N": "Ano", "D3C": "Variavel Codigo", "D3N": "Variavel", "D4N": "Cultura"}, inplace=True)

#Excluindo a primeira linha da planilha
dados_soja = dados_soja.drop(0)

dados_soja.head()

,Nível Territorial (Código),Nível Territorial (Nome),Unidade de Medida (Código),Unidade de Medida (Nome),Valor,Municipio (Código),Municipio,Ano Codigo,Ano,Variavel Codigo,Variavel,D4C,Cultura
1,6,Município,33,Quilogramas por Hectare,-,3500105,Adamantina - SP,2014,2014,112,Rendimento médio da produção,40124,Soja (em grão)
2,6,Município,1006,Hectares,-,3500105,Adamantina - SP,2014,2014,216,Área colhida,40124,Soja (em grão)
3,6,Município,33,Quilogramas por Hectare,-,3500105,Adamantina - SP,2015,2015,112,Rendimento médio da produção,40124,Soja (em grão)
4,6,Município,1006,Hectares,-,3500105,Adamantina - SP,2015,2015,216,Área colhida,40124,Soja (em grão)
5,6,Município,33,Quilogramas por Hectare,1800,3500105,Adamantina - SP,2016,2016,112,Rendimento médio da produção,40124,Soja (em grão)

In [55]:
#Verificando e excluindo duplicados
dados_soja.duplicated().sum()

np.int64(0)

In [56]:
#Alterando valores nulos para 0
dados_soja = dados_soja.fillna(0)